<!DOCTYPE html>
<html>
<head>
 <title>MONTHLY WAF REPORT</title>
 <style type="text/css">
  .page-break {
    page-break-after: always;    
  } 
 @page { margin: 100px 25px; }
    header { position: fixed; 
       top: -60px; 
       left: 0px; right: 0px; 
       background-color: lightblue; 
       height: 50px; 
    }
   #footer { position: fixed; 
        bottom: -60px; 
        left: 0px; 
        right: 0px; 
        height: 50px;   
        width:100%; 
        text-align: center;     
    }
    .datetime{
     float:left;
     text-align: left;
     width:40%;
    }
    .pic{
     width:40%;
     float:right;
     text-align: right;
    }
    #page-number:before{     
     display: inline-block;
     margin:0 auto;
     width:20%;
     content: "Page " counter(page);
     clear: both;
     
    }
   
    p { page-break-after: always; }
    p:last-child { page-break-after: never; }
 </style>
<!--  -->

</head>
<body>


 <header><img src="images/logo_visionet.png" style="width: 250px; height: 50px;"></header>
<div id="footer">
  <div class="datetime"><?php date_default_timezone_set("Asia/Bangkok"); echo date("Y-m-d h:i:sa")?></div>
   <div class="pic"> <?php echo "PIC: ", session()->get('Username'); ?> </div>
   <div id="page-number"></div>
   </div>
 <main>

<!--   PAGE 1 -->
 
<div style=" justify-content: center;
  text-align: center;margin-top: 200px;margin-bottom: 200px;">
    
    <h1 style="font-size: 40px;">REPORT</h1>
    <h2 style="font-size: 35px;"><?php $ResultLogServer = json_decode(Session::get("ResultLogServer")); echo $ResultLogServer->Month; ?></h2>
    <h3 style="font-size: 30px;">V 1.1.1</h3>
  </div>


<div style="position: fixed;bottom: 300px;">
 <!-- <h1 style="background-color: : ">
  
  <img src="images/logo_visionet.png" style="width: 250px; height: 50px;">
</h1> -->
<h3 style="text-align: left;font-family: Arial Black;font-style: bold;color:#ff8100;">Monthly WAF Report</h2>
<!-- <h3 style="text-align: left;font-family: Arial Black;font-style: bold;">Detail Report :</h3> -->

  
<table style="font-size: 24px;font-family: Times New Roman">
  <tr>
    <td style="width:100px"><label>Server</label> </td>
    <td>: <label id=""><?php 
    $ResultLogServer = json_decode(Session::get("ResultLogServer")); 
    echo 
    $ResultLogServer->ServerDetail->Domain;
     ?>
       
     </label></td>
  </tr>
  <tr>
    <td style="width:100px"><label>IP Server</label> </td>
    <td>: <label id=""><?php 
    $ResultLogServer = json_decode(Session::get("ResultLogServer")); 
    echo 
    $ResultLogServer->ServerDetail->IP;
     ?>
       
     </label><label>:<?php 
    $ResultLogServer = json_decode(Session::get("ResultLogServer")); 
    echo 
    $ResultLogServer->ServerDetail->PortsOpen;
     ?></label></td>
  </tr>
  <tr>
    <td><label>PIC</label></td>
    <td>: <label>
           <?php echo session()->get('Username'); ?>
    </label></td>
  </tr>
  <tr>
    <td><label>Generated</label></td>
    <td>: <label> <?php
$t=time();
echo(date("Y-m-d h:i:sa",$t));
?></label></td>
  </tr>
</table>
</div>

<!-- END OF PAGE 1 -->

<!-- PAGE 2 -->

<p>

  <h2 style="text-align: center;font-family: Arial Black;font-style: bold;color:#ff8100;">WAF Technical Report</h2>
  <hr noshade>
  <table>
    <tr>
      <td>1.</td>
      <td>This WAF Report is Generated by the system and cant be changed at the moment.</td>
    </tr>
    <tr>
      <td>2.</td>
      <td>This WAF Report is Generated based on server , all the data and value in this report depends on the server.</td>
    </tr>
    <tr>
      <td>3.</td>
      <td>This version of report is the Alpha version of the report and still developing at this time.</td>
    </tr>
    <tr>
      <td>4.</td>
      <td>This reporting include several part :</td>
    </tr>
    <tr>
      <td>i</td>
      <td>Page 1 : Cover of Report</td>
    </tr>
    <tr>
      <td>ii</td>
      <td>Page 2 : Term and Condition of Report</td>
    </tr>
    <tr>
      <td>iii</td>
      <td>Page 3 : Overview / Summary of Report</td>
    </tr>
    <tr>
      <td>iV</td>
      <td>Page 4-5 : Content Of Report</td>
    </tr>
    
  </table>

<h4>Note : All this Term and Condition made by purposes to gave an example how it looks like when it's filled , all the condition can be changed sometimes depends on the request.</h4>
</p>

<!-- END OF PAGE 2 -->


<!-- Page 3 -->
<p>

 <h2 style="text-align: center;font-family: Arial Black;font-style: bold;color:#ff8100;">Overview / Summary Report</h2>
 <hr noshade>

 <table style="font-size: 24px;font-family: Times New Roman">
  <tr>
    <td style="width:100px"><label>Server</label> </td>
    <td>: <label id=""><?php 
    $ResultLogServer = json_decode(Session::get("ResultLogServer")); 
    echo 
    $ResultLogServer->ServerDetail->Domain;
     ?>
       
     </label></td>
  </tr>
  <tr>
    <td style="width:100px"><label>IP Server</label> </td>
    <td>: <label id=""><?php 
    $ResultLogServer = json_decode(Session::get("ResultLogServer")); 
    echo 
    $ResultLogServer->ServerDetail->IP;
     ?>
       
     </label><label>:<?php 
    $ResultLogServer = json_decode(Session::get("ResultLogServer")); 
    echo 
    $ResultLogServer->ServerDetail->PortsOpen;
     ?></label></td>
  </tr>

</table>

<h3 style="text-align: center;c">Summary</h3>

<table style="border: solid ;border-color: #ff8100;margin: auto">
  <tr>
     <td style="border: solid ;border-color: #ff8100;width: 50px">No.</td>
    <td style="border: solid ;border-color: #ff8100;width: 50px">Month</td>
    <td style="border: solid ;border-color: #ff8100;width: 150px">Attempted Attack</td>
    <td style="border: solid ;border-color: #ff8100;width: 150px">Total Access Log</td>
    <td style="border: solid ;border-color: #ff8100;width: 150px">Freq.UserAgent</td>
  </tr>
  <?php
$i=1;

   $ResultLogServer = json_decode(Session::get("ResultLogServer"));

               echo"<tr>
                <td style='border: solid ;border-color: #ff8100;width: 50px'>".$i."</td>
                <td style='border: solid ;border-color: #ff8100;width: 50px'>JUN</td>
                <td style='border: solid ;border-color: #ff8100;width: 150px'>".$ResultLogServer->LogCount."</td>
                <td style='border: solid ;border-color: #ff8100;width: 150px'>".$ResultLogServer->AccessLogCount."</td>
                <td style='border: solid ;border-color: #ff8100;width: 150px'>".$ResultLogServer->FreqUA."</td>
               </tr>";
            $i++;
            
           
       

 ?>


</table>
</p>

<!-- end of page 3 -->

<!-- PAGE 4 -->
<p>
<CENTER><h1 style="font-family: Arial Black;font-style: bold;color:#ff8100;">Security/Alarm</h1></CENTER>
<hr noshade>
<br><br>

<table style="border: solid 2px;border-color: #ff8100; float:left;">
  <tr>
    <th style="background-color:#ff8100;float: center;"><label style="color: white;">No.</label></th>
    <th style="background-color:#ff8100;float: center;"><label style="color: white; width:200px;">Event Name</label></th>
    <th style="background-color:#ff8100;float: center;"><label style="color: white;">TimeStamp</label></th>
    <th style="background-color:#ff8100;float: center;"><label style="color: white;">Source</label></th>
    <th style="background-color:#ff8100;float: center;"><label style="color: white;">Destination</label></th>
    <th style="background-color:#ff8100;float: center;"><label style="color: white;">Risk</label></th>
  </tr>
  <?php      
   $ResultLogServer = json_decode(Session::get("ResultLogServer"));
   $i=1;
                foreach ($ResultLogServer->ResultSecLog as $key => $value) {
                 echo "
                        <tr>
                          <td style='border: solid ;border-color: #ff8100;width: 5px'>".$i."</td>
                          <td style='border: solid ;border-color: #ff8100;width: 200px'>".$value->transaction->messages[0]->message."</td>
                          <td style='border: solid ;border-color: #ff8100;width: 150px'>".$value->transaction->time_stamp."</td>
                          <td style='border: solid ;border-color: #ff8100;width: 150px'>".$value->transaction->client_ip."</td>
                          <td style='border: solid ;border-color: #ff8100;width: 150px'>".$value->transaction->host_ip.":".$value->transaction->host_port."</td>
                          <td style='border: solid ;border-color: #ff8100;width: 5px'>1</td>
                        </tr>";
                        $i++;
                }
            
            
  ?>
</table>


</p>
<!-- end of page 4 -->

<!-- PAGE 5 -->
<p>

<CENTER><h1 style="font-family: Arial Black;font-style: bold;color:#ff8100;">Access Log</h1></CENTER>
<hr noshade>
<br><br>
<h3>Total Access Logs : <?php    $ResultLogServer = json_decode(Session::get("ResultLogServer"));
  echo $ResultLogServer->AccessLogCount;

 ?></h3>
 <div>
<table style="border: solid 2px;border-color: #ff8100; float:left;">
  <tr>
    <th style="background-color:#ff8100;float: center;"><label style="color: white;">Methods</label></th>
    <th style="background-color:#ff8100;float: center;"><label style="color: white;">Count</label></th>
  </tr>
  <?php


   $ResultLogServer = json_decode(Session::get("ResultLogServer"));

            echo"<tr>
             <td style='border: solid 2px;border-color: #ff8100;width: 150px'>POST</td>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>".$ResultLogServer->PostCount."</td>
                </tr>
                <tr>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>GET</td>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>".$ResultLogServer->GetCount."</td>
                </tr>";
            
  ?>
</table>

<table style="border: solid 2px;border-color: #ff8100; float:right;">
 <tr>
  <th style="background-color:#ff8100;float: center;"><label style="color: white;">User Agent</label></th>
  <th style="background-color:#ff8100;float: center;"><label style="color: white;">Count</label></th>
 </tr>
  <?php


   $ResultLogServer = json_decode(Session::get("ResultLogServer"));

            echo"<tr>
             <td style='border: solid 2px;border-color: #ff8100;width: 150px'>Firefox</td>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>".$ResultLogServer->FirefoxCount."</td>
                </tr>
                <tr>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>Safari</td>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>".$ResultLogServer->SafariCount."</td>
                </tr>
                <tr>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>Chrome</td>
                <td style='border: solid 2px;border-color: #ff8100;width: 150px'>".$ResultLogServer->ChromeCount."</td>
                </tr>";
            
  ?>
</table>
</div>
</p>
<!-- end of page 5 -->
</main>
</body>
</html>